[WIN32K]: Addendum to r75332 : fix variable usage without initialization error C4700 (certainly due to a copy-paste error), caught by MSVC compiler... CORE-13536
git-svn-id: file:///srv/svn/reactos/trunk@75337 97493ccd-5924-5043-b1f5-66cb403b36ce